server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # ► ROUTE STUDIO : toute l’API
        - id: studio-service
          uri: lb://studio
          predicates:
            - Path=/studio/**

        # ► ROUTE STUDIO : Swagger (UI + assets + docs)
        - id: studio-swagger
          uri: lb://studio
          predicates:
            - Path=/studio/swagger-ui.html,/studio/swagger-ui/index.html,/studio/swagger-ui/**,/studio/v3/api-docs,/studio/v3/api-docs/**
          filters:
            - StripPrefix=1

        # ► ROUTE FILMS : toute l’API
        - id: films-service
          uri: lb://films
          predicates:
            - Path=/films/**

        # ► ROUTE FILMS : Swagger (UI + assets + docs)
        - id: films-swagger
          uri: lb://films
          predicates:
            - Path=/films/swagger-ui.html,/films/swagger-ui/index.html,/films/swagger-ui/**,/films/v3/api-docs,/films/v3/api-docs/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true          # /actuator/gateway/**
  endpoints:
    web:
      exposure:
        include: gateway,health,info
