server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        # ► ROUTE STUDIO (API + SWAGGER)
        - id: studio-service
          uri: lb://studio
          predicates:
            - Path=/studio/**           # toutes les API
        - id: studio-swagger
          uri: lb://studio
          predicates:
            - Path=/studio/swagger-ui.html,
              /studio/swagger-ui/index.html,
              /studio/swagger-ui/**,
              /studio/api-docs/**,
              /studio/v3/api-docs/**
          filters:
            - StripPrefix=1

        # ► ROUTE FILMS (API + SWAGGER)
        - id: films-service
          uri: lb://films
          predicates:
            - Path=/films/**
        - id: films-swagger
          uri: lb://films
          predicates:
            - Path=/films/swagger-ui.html,
              /films/swagger-ui/index.html,
              /films/swagger-ui/**,
              /films/api-docs/**,
              /films/v3/api-docs/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true      # ← OBLIGATOIRE pour exposer /actuator/gateway/**
  endpoints:
    web:
      exposure:
        include: gateway,health,info
