server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # ► STUDIO – API
        - id: studio-service
          uri: lb://studio
          predicates: [ Path=/studio/** ]
          filters:   [ StripPrefix=1, PreserveHostHeader ]

        # ► STUDIO – Swagger (UI + assets + docs)
        - id: studio-swagger
          uri: lb://studio
          predicates:
            - Path=/studio/swagger-ui.html,/studio/swagger-ui/**,
              /studio/v3/api-docs,/studio/v3/api-docs/**
          filters:   [ StripPrefix=1, PreserveHostHeader ]

        # ► FILMS – API
        - id: films-service
          uri: lb://films
          predicates: [ Path=/films/** ]
          filters:   [ StripPrefix=1, PreserveHostHeader ]

        # ► FILMS – Swagger (UI + assets + docs)
        - id: films-swagger
          uri: lb://films
          predicates:
            - Path=/films/swagger-ui.html,/films/swagger-ui/**,
              /films/v3/api-docs,/films/v3/api-docs/**
          filters:   [ StripPrefix=1, PreserveHostHeader ]

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway,health,info
