server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://film-db:27017/filmsdb

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
    config-url: /api-docs/swagger-config
  api-docs:
    path: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
