server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://film-db:27017/filmsdb

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs          # (chemin par défaut, on le laisse)
  swagger-ui:
    path: /swagger-ui.html      # URL finale à appeler
    use-root-path: true         # IMPORTANT : ressources statiques résolues correctement
    config-url: /v3/api-docs/swagger-config


eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
