server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://film-db:27017/filmsdb

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
    add-server: false        # ← SUPPRIME le bloc "servers"
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: false
    disable-swagger-default-url: true
    config-url: /films/v3/api-docs/swagger-config
    urls:
      - name: films                # intitulé affiché dans le menu
        url: /films/v3/api-docs    # ← spec réelle via Gateway





eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
