server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://film-db:27017/filmsdb

  # --- AJOUT KAFKA CONSOMMATEUR ---
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: films
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages:  "*"

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
    add-server: false
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: false
    disable-swagger-default-url: true
    config-url: /films/v3/api-docs/swagger-config
    urls:
      - name: films
        url: /films/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      studioService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      studioService:
        maxAttempts: 3
        waitDuration: 500ms

feign:
  client:
    config:
      default:
        loggerLevel: basic
