server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://film-db:27017/filmsdb

logging:
  level:
    root: info

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: false            # garde le /films/
    disable-swagger-default-url: true
    config-url: /films/v3/api-docs/swagger-config   # ← PRÉFIXE CORRECT





eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
