server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://studio-db:3306/studiodb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
    config-url: /api-docs/swagger-config
  api-docs:
    path: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
