server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://studio-db:3306/studiodb
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
    add-server: false        # ← SUPPRIME le bloc "servers"
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: false
    disable-swagger-default-url: true
    config-url: /studio/v3/api-docs/swagger-config
    urls:
      - name: studio
        url: /studio/v3/api-docs




eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
